### ISSUE TITLE
Unable to clone the master branch

### ISSUE THREAD

**Issue by proletarius101** [ProtonVPN/python-proton-vpn-api-core#2]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

The master branch (as of [a64a2a1](https://github.com/ProtonVPN/python-proton-vpn-api-core/commit/a64a2a1761f7e3626267861166ba42265115d2c5)) has a submodule `scripts/devtools` referring to a private repository on GitHub.com, which prevents this repository from being cloned by the general public.

**Comment by calexandru2018** [comment]
@proletarius101 I don't have any issues cloning via https or ssh, works fine for me 👍🏻

**Comment by calexandru2018** [comment]
Ah ok understood. Yeah those are some internal tools that we use mainly for speeding up our dev process and our CI. 👍🏻
